version: "2"
services:
  app:
    build: .
    # command: pm2 ./backend/app/server.js --watch
    environment:
      NODE_ENV: prd
    env_file:
      - ./.env.be.dev
    # depends_on:
    #   - postgres
    ports:
      - 8080:8080
      - 80:80
    volumes:
      - .:/usr/src/app/backeEnd
      - /usr/src/app/backeEnd/node_modules
      - shared-volume:/usr/src/app/frontEnd

  # nginx:
  #   image: nginx:latest
  #   links:
  #     - app
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - shared-volume:/usr/src/app/frontEnd

  # postgres:
  #   image: postgres:14.1-alpine
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DB=${POSTGRES_DB}
  #   ports:
  #     - ${POSTGRES_PORT}:${POSTGRES_PORT}
  #   volumes:
  #     - ./backend/config/database/database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
  #     - ./data:/var/lib/postgresql/data

volumes:
    shared-volume:
